language: julia
os:
  - linux
  - osx
julia:
  - 0.4
notifications:
  email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - nodisp=''; if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xvfb && nodisp='xvfb-run'; fi
    - $nodisp julia -e 'Pkg.clone(pwd()); Pkg.build("FileIO"); Pkg.test("MatlabCompat"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("FileIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
